### ISSUE TITLE
The performance in the paper is inconsistent with that the code does.

### ISSUE THREAD

**Issue by newlei** [HKUDS/LightGCL#18]
**On Yelp,  the performance of the [paper](https://openreview.net/pdf?id=FKXVK9dyMM) is low (Recall@20: 0.0793 Ndcg@20:0.0668 Recall@40:0.1292 Ndcg@40:0.0852). The actual running is high( Recall@20: 0.1005596274687573 Ndcg@20: 0.08650433827615736 Recall@40: 0.1597782188737718 Ndcg@40: 0.10812958940033758).**

The details of the actual running is following:
```
Test of epoch 96 : Recall@20: 0.10051406435437939 Ndcg@20: 0.08627444271978929 Recall@40: 0.15986645365267868 Ndcg@40: 0.10792282233659943
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 262/262 [00:24<00:00, 10.64it/s]
Epoch: 97 Loss: 2.5118775304037197 Loss_r: 0.3031725097476071 Loss_s: 2.2050413157193716
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 262/262 [00:24<00:00, 10.68it/s]
Epoch: 98 Loss: 2.511937270637687 Loss_r: 0.30322049376163773 Loss_s: 2.205053930974189
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 262/262 [00:24<00:00, 10.59it/s]
Epoch: 99 Loss: 2.5120028903466145 Loss_r: 0.30331670953572254 Loss_s: 2.205021769945858
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 116/116 [00:08<00:00, 13.75it/s]
-------------------------------------------
Test of epoch 99 : Recall@20: 0.1005596274687573 Ndcg@20: 0.08650433827615736 Recall@40: 0.1597782188737718 Ndcg@40: 0.10812958940033758
-------------------------------------------
Final test: Recall@20: 0.1005596274687573 Ndcg@20: 0.08650433827615736 Recall@40: 0.1597782188737718 Ndcg@40: 0.10812958940033758
```

**On ML-10M, the performance of the [paper](https://openreview.net/pdf?id=FKXVK9dyMM)  is high (Recall@20: 0.2613  Ndcg@20:0.3106 Recall@40:0.3799 Ndcg@40:0.3387 1). The actual running is low (Recall@20: 0.22966711970088424 Ndcg@20: 0.28407235346796683 Recall@40: 0.31642916993719605 Ndcg@40: 0.30047428117834374)**

The details of the actual running is following:
```
Epoch: 98 Loss: 2.513269269026951 Loss_r: 0.3047634800356546 Loss_s: 2.18953038922104
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1709/1709 [07:04<00:00,  4.03it/s]
Epoch: 99 Loss: 2.5132692800480556 Loss_r: 0.3047331753462082 Loss_s: 2.1895613562928227
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 273/273 [00:23<00:00, 11.86it/s]
-------------------------------------------
Test of epoch 99 : Recall@20: 0.22966711970088424 Ndcg@20: 0.28407235346796683 Recall@40: 0.31642916993719605 Ndcg@40: 0.30047428117834374
-------------------------------------------
Final test: Recall@20: 0.22966711970088424 Ndcg@20: 0.28407235346796683 Recall@40: 0.31642916993719605 Ndcg@40: 0.30047428117834374
```

**Comment by Re-bin** [comment]
Hi, thank you for reading our paper :)

The reported results and the results produced by the released codes are different because after we submitted our paper.
Please check [issue9](https://github.com/HKUDS/LightGCL/issues/9) for more detials.

**Comment by newlei** [comment]
Thank you for your quick and kind response.

Additionally, I have two questions.

1. While the answer to [issue9](https://github.com/HKUDS/LightGCL/issues/9) explains the reason for the performance improvement, the cause of the decrease in performance on the ML-10M dataset remains unclear.

2. In [issue9](https://github.com/HKUDS/LightGCL/issues/9), the author~(Xuheng Cai) made a promise to update the results on arXiv. However, upon checking, I found that the results on the [arXiv](https://arxiv.org/abs/2302.08191)  page have not been updated yet. If the results are updated, it will help alleviate any doubts about the results.

Thanks again for your kind response.

> Hi, thank you for reading our paper :)
> 
> The reported results and the results produced by the released codes are different because after we submitted our paper. Please check [issue9](https://github.com/HKUDS/LightGCL/issues/9) for more detials.

**Comment by Rick-Cai** [comment]
Hi, thanks for pointing this out. Yes, in our experiment we did find that the performance on ML-10M decreased after adopting the new setting. Specifically, the best parameters we found are: lambda_1=0.2, temp=0.5. And since the new setting directly samples pos and neg item pairs based on interactions instead of users, and the ML-10M dataset is very dense with too many interactions, using the default batch size 256 will take an unreasonably long time, so we are running with a batch size of 16384. The results are:

R@20: 0.2535  N@20: 0.2979  R@40: 0.3480  N@40: 0.3180

which is still lower than the performance reported in the paper (old setting). The cause is rather unclear to us either. One possibility is that due to the high density and large number of interactions of the ML-10M dataset (it is the densest of the 5 datasets), the old sampling method (sampling a fixed number of interactions for each user) actually only sampled a small fractions of the interactions when training. On the contrary, the new sampling method (sampling interactions directly) takes most of the interactions into training. If the interaction data are of low quality (e.g. contain a lot of noisy interactions), it will have a much more negative impact on the new setting than the old setting. Of course, this is rather difficult to verify.

We have been collecting feedbacks for the new arXiv version, and there were some delays. It turned out that there are some other minor issues to repair too (e.g. the dataset statistics). We will update the arXiv in a few days. Thank you again for bring up this important issue.

**Comment by newlei** [comment]
Thank you so much for your kind response. Looking forward to your updated results on arXiv [page](https://arxiv.org/abs/2302.08191).

I have a small request, which may sound demanding. It would be greatly appreciated if the code with the old settings could also be made available in the [LightGCL repository](https://github.com/HKUDS/LightGCL). This would make the LightGCL repository even more comprehensive.

**Comment by Rick-Cai** [comment]
Thank you for the suggestion. I have just uploaded the old setting codes to the repository, under the "old_setting" directory, for your reference.

**Comment by newlei** [comment]
Thank you so much!
I will close this issue.
